In [37]:
# importamos las librerías que necesitamos

# Tratamiento de datos
import pandas as pd
import numpy as np
from IPython.display import display


# Librerías de visualización
import seaborn as sns
import matplotlib.pyplot as plt

In [38]:
# ver todas las columnas
pd.set_option('display.max_columns', None)

In [40]:
# ver todas las filas
pd.set_option('display.max_rows', None)

In [41]:
df = pd.read_csv("ABC_data_sin_nulos.csv")

In [42]:
df.head()

,attrition,businesstravel,dailyrate,department,distancefromhome,education,educationfield,employeenumber,environmentsatisfaction,gender,jobinvolvement,joblevel,jobrole,jobsatisfaction,maritalstatus,monthlyincome,monthlyrate,numcompaniesworked,overtime,percentsalaryhike,performancerating,relationshipsatisfaction,standardhours,stockoptionlevel,totalworkingyears,trainingtimeslastyear,worklifebalance,yearsatcompany,yearssincelastpromotion,yearswithcurrmanager,datebirth,salary,roledepartament,remotework
0,No,Unknown,2015.722222,Unknown,6.0,3.0,Unknown,1.0,1.0,0.0,3.0,5.0,resEArch DIREcToR,3.0,Unknown,"16280,83$","42330,17$",7.0,No,13.0,3.0,3.0,Full Time,0.0,10.0,5.0,3.0,20.0,15.0,15.0,1972.0,"195370,00$",Unknown,Yes
1,No,Unknown,2063.388889,Unknown,1.0,4.0,Life Sciences,2.0,3.0,0.0,2.0,5.0,ManAGeR,3.0,Unknown,Unknown,"43331,17$",0.0,Unknown,14.0,3.0,1.0,Unknown,1.0,34.0,5.0,3.0,33.0,11.0,9.0,1971.0,"199990,00$",Unknown,1
2,No,travel_rarely,1984.253968,Research & Development,4.0,2.0,Technical Degree,3.0,3.0,0.0,3.0,5.0,ManaGER,4.0,Married,Unknown,"41669,33$",1.0,No,11.0,3.0,4.0,Unknown,0.0,22.0,3.0,3.0,22.0,11.0,15.0,1981.0,"192320,00$",ManaGER - Research & Development,1
3,No,travel_rarely,1771.404762,Unknown,2.0,4.0,Medical,4.0,1.0,1.0,3.0,4.0,ReseArCH DIrECtOr,3.0,Married,"14307,50$","37199,50$",3.0,Unknown,19.0,3.0,2.0,Full Time,2.0,10.0,2.0,3.0,20.0,5.0,6.0,1976.0,"171690,00$",Unknown,False
4,No,Unknown,1582.771346,Unknown,3.0,3.0,Technical Degree,5.0,1.0,1.0,4.0,4.0,sAleS EXECUtIve,1.0,Divorced,"12783,92$","33238,20$",2.0,No,12.0,3.0,4.0,Unknown,1.0,10.0,5.0,3.0,19.0,2.0,8.0,1977.0,Unknown,Unknown,0

####

#### Columna remotework

Normalizar a valores yes/ no.

In [43]:
# Normalizar la columna 'remotework' a valores yes/no:

#1.Inspeccionamos primero los valores únicos
df['remotework'].unique()

array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [44]:
#2. Normalizamos 
df['remotework'] = (
    df['remotework']
    .astype(str)       # convertir a texto
    .str.strip()       # quitar espacios
    .str.lower()       # pasar a minúsculas
    .replace({         # mapear valores conocidos
        'yes': 'yes',
        'true': 'yes',
        '1': 'yes',
        'false': 'no',
        '0': 'no'
    })
)

#3.Verificamos el resultado final
print(df['remotework'].value_counts())

remotework
yes    1000
no      614
Name: count, dtype: int64

In [45]:
df.head()

,attrition,businesstravel,dailyrate,department,distancefromhome,education,educationfield,employeenumber,environmentsatisfaction,gender,jobinvolvement,joblevel,jobrole,jobsatisfaction,maritalstatus,monthlyincome,monthlyrate,numcompaniesworked,overtime,percentsalaryhike,performancerating,relationshipsatisfaction,standardhours,stockoptionlevel,totalworkingyears,trainingtimeslastyear,worklifebalance,yearsatcompany,yearssincelastpromotion,yearswithcurrmanager,datebirth,salary,roledepartament,remotework
0,No,Unknown,2015.722222,Unknown,6.0,3.0,Unknown,1.0,1.0,0.0,3.0,5.0,resEArch DIREcToR,3.0,Unknown,"16280,83$","42330,17$",7.0,No,13.0,3.0,3.0,Full Time,0.0,10.0,5.0,3.0,20.0,15.0,15.0,1972.0,"195370,00$",Unknown,yes
1,No,Unknown,2063.388889,Unknown,1.0,4.0,Life Sciences,2.0,3.0,0.0,2.0,5.0,ManAGeR,3.0,Unknown,Unknown,"43331,17$",0.0,Unknown,14.0,3.0,1.0,Unknown,1.0,34.0,5.0,3.0,33.0,11.0,9.0,1971.0,"199990,00$",Unknown,yes
2,No,travel_rarely,1984.253968,Research & Development,4.0,2.0,Technical Degree,3.0,3.0,0.0,3.0,5.0,ManaGER,4.0,Married,Unknown,"41669,33$",1.0,No,11.0,3.0,4.0,Unknown,0.0,22.0,3.0,3.0,22.0,11.0,15.0,1981.0,"192320,00$",ManaGER - Research & Development,yes
3,No,travel_rarely,1771.404762,Unknown,2.0,4.0,Medical,4.0,1.0,1.0,3.0,4.0,ReseArCH DIrECtOr,3.0,Married,"14307,50$","37199,50$",3.0,Unknown,19.0,3.0,2.0,Full Time,2.0,10.0,2.0,3.0,20.0,5.0,6.0,1976.0,"171690,00$",Unknown,no
4,No,Unknown,1582.771346,Unknown,3.0,3.0,Technical Degree,5.0,1.0,1.0,4.0,4.0,sAleS EXECUtIve,1.0,Divorced,"12783,92$","33238,20$",2.0,No,12.0,3.0,4.0,Unknown,1.0,10.0,5.0,3.0,19.0,2.0,8.0,1977.0,Unknown,Unknown,no

#### Columna gender

Normalizar a valores M/F.

In [46]:
# Normalizar la columna gender a valores M/F:

#1.Inspeccionamos primero los valores únicos
print(df['gender'].unique())

[0. 1.]

In [47]:
#2. Normalizamos 
df['gender'] = (
    df['gender']
    .astype(str)        # aseguramos texto
    .str.strip()        # quitamos espacios
    .str.lower()        # pasamos a minúsculas
    .replace({
        'male': 'M',
        'm': 'M',
        '1': 'M',
        'hombre': 'M',
        'man': 'M',
        'female': 'F',
        'f': 'F',
        '0': 'F',
        'mujer': 'F',
        'woman': 'F'
    })
)

#3. Verificamos el resultado
print(df['gender'].value_counts())

gender
0.0    971
1.0    643
Name: count, dtype: int64

In [48]:
df.head()

,attrition,businesstravel,dailyrate,department,distancefromhome,education,educationfield,employeenumber,environmentsatisfaction,gender,jobinvolvement,joblevel,jobrole,jobsatisfaction,maritalstatus,monthlyincome,monthlyrate,numcompaniesworked,overtime,percentsalaryhike,performancerating,relationshipsatisfaction,standardhours,stockoptionlevel,totalworkingyears,trainingtimeslastyear,worklifebalance,yearsatcompany,yearssincelastpromotion,yearswithcurrmanager,datebirth,salary,roledepartament,remotework
0,No,Unknown,2015.722222,Unknown,6.0,3.0,Unknown,1.0,1.0,0.0,3.0,5.0,resEArch DIREcToR,3.0,Unknown,"16280,83$","42330,17$",7.0,No,13.0,3.0,3.0,Full Time,0.0,10.0,5.0,3.0,20.0,15.0,15.0,1972.0,"195370,00$",Unknown,yes
1,No,Unknown,2063.388889,Unknown,1.0,4.0,Life Sciences,2.0,3.0,0.0,2.0,5.0,ManAGeR,3.0,Unknown,Unknown,"43331,17$",0.0,Unknown,14.0,3.0,1.0,Unknown,1.0,34.0,5.0,3.0,33.0,11.0,9.0,1971.0,"199990,00$",Unknown,yes
2,No,travel_rarely,1984.253968,Research & Development,4.0,2.0,Technical Degree,3.0,3.0,0.0,3.0,5.0,ManaGER,4.0,Married,Unknown,"41669,33$",1.0,No,11.0,3.0,4.0,Unknown,0.0,22.0,3.0,3.0,22.0,11.0,15.0,1981.0,"192320,00$",ManaGER - Research & Development,yes
3,No,travel_rarely,1771.404762,Unknown,2.0,4.0,Medical,4.0,1.0,1.0,3.0,4.0,ReseArCH DIrECtOr,3.0,Married,"14307,50$","37199,50$",3.0,Unknown,19.0,3.0,2.0,Full Time,2.0,10.0,2.0,3.0,20.0,5.0,6.0,1976.0,"171690,00$",Unknown,no
4,No,Unknown,1582.771346,Unknown,3.0,3.0,Technical Degree,5.0,1.0,1.0,4.0,4.0,sAleS EXECUtIve,1.0,Divorced,"12783,92$","33238,20$",2.0,No,12.0,3.0,4.0,Unknown,1.0,10.0,5.0,3.0,19.0,2.0,8.0,1977.0,Unknown,Unknown,no

#### Normalizar todas las columnas categóricas

In [49]:
# Creamos una función para renombrar todas las columnas
import re

def normalizar_nombres_columnas(df):
    """
    Normaliza nombres de columnas:
      - Inserta '_' entre palabras (detecta camelCase y letras/números)
      - Capitaliza la primera letra de cada palabra
    """
    nuevas_columnas = []

    for col in df.columns:
        # 1. Elimina espacios al inicio y final
        col = col.strip()

        # 2. Inserta '_' entre palabras (camelCase o letras/números)
        col = re.sub(r'(?<=[a-z])(?=[A-Z])', '_', col)     # minúscula→Mayúscula
        col = re.sub(r'(?<=[a-zA-Z])(?=[0-9])', '_', col)  # letra→dígito
        col = re.sub(r'(?<=[0-9])(?=[a-zA-Z])', '_', col)  # dígito→letra

        # 3. Pasar a minúsculas
        col = col.lower()

        # 4. Capitalizar la primera letra de cada palabra
        partes = col.split('_')
        partes = [p.capitalize() for p in partes]

        # 5. Volver a unir con '_'
        nuevo_nombre = '_'.join(partes)

        nuevas_columnas.append(nuevo_nombre)

    df.columns = nuevas_columnas
    return df


# Uso: aplicar y guardar la función sobre df_limpio
df = normalizar_nombres_columnas(df)

In [50]:
df.head()

,Attrition,Businesstravel,Dailyrate,Department,Distancefromhome,Education,Educationfield,Employeenumber,Environmentsatisfaction,Gender,Jobinvolvement,Joblevel,Jobrole,Jobsatisfaction,Maritalstatus,Monthlyincome,Monthlyrate,Numcompaniesworked,Overtime,Percentsalaryhike,Performancerating,Relationshipsatisfaction,Standardhours,Stockoptionlevel,Totalworkingyears,Trainingtimeslastyear,Worklifebalance,Yearsatcompany,Yearssincelastpromotion,Yearswithcurrmanager,Datebirth,Salary,Roledepartament,Remotework
0,No,Unknown,2015.722222,Unknown,6.0,3.0,Unknown,1.0,1.0,0.0,3.0,5.0,resEArch DIREcToR,3.0,Unknown,"16280,83$","42330,17$",7.0,No,13.0,3.0,3.0,Full Time,0.0,10.0,5.0,3.0,20.0,15.0,15.0,1972.0,"195370,00$",Unknown,yes
1,No,Unknown,2063.388889,Unknown,1.0,4.0,Life Sciences,2.0,3.0,0.0,2.0,5.0,ManAGeR,3.0,Unknown,Unknown,"43331,17$",0.0,Unknown,14.0,3.0,1.0,Unknown,1.0,34.0,5.0,3.0,33.0,11.0,9.0,1971.0,"199990,00$",Unknown,yes
2,No,travel_rarely,1984.253968,Research & Development,4.0,2.0,Technical Degree,3.0,3.0,0.0,3.0,5.0,ManaGER,4.0,Married,Unknown,"41669,33$",1.0,No,11.0,3.0,4.0,Unknown,0.0,22.0,3.0,3.0,22.0,11.0,15.0,1981.0,"192320,00$",ManaGER - Research & Development,yes
3,No,travel_rarely,1771.404762,Unknown,2.0,4.0,Medical,4.0,1.0,1.0,3.0,4.0,ReseArCH DIrECtOr,3.0,Married,"14307,50$","37199,50$",3.0,Unknown,19.0,3.0,2.0,Full Time,2.0,10.0,2.0,3.0,20.0,5.0,6.0,1976.0,"171690,00$",Unknown,no
4,No,Unknown,1582.771346,Unknown,3.0,3.0,Technical Degree,5.0,1.0,1.0,4.0,4.0,sAleS EXECUtIve,1.0,Divorced,"12783,92$","33238,20$",2.0,No,12.0,3.0,4.0,Unknown,1.0,10.0,5.0,3.0,19.0,2.0,8.0,1977.0,Unknown,Unknown,no

In [51]:
# 1. Identificamos columnas numéricas
columnas_numericas = df.select_dtypes(include="number").columns
print("Columnas numéricas:", list(columnas_numericas))

# 2. Definimos una función para normalizar números
def normalizar_numeros(columna):
    # Reemplazamos comas por puntos y convertimos a numérico
    columna = columna.astype(str).str.replace(",", ".", regex=False)
    columna = pd.to_numeric(columna, errors="coerce")  # convierte a número
    return columna.round(2)  # redondeamos a 2 decimales

# 3. Aplicamos la función a cada columna numérica
for col in columnas_numericas:
    df[col] = normalizar_numeros(df[col])

# 4. Revisamos las primeras filas
df[columnas_numericas].head()

Columnas numéricas: ['Dailyrate', 'Distancefromhome', 'Education', 'Employeenumber', 'Environmentsatisfaction', 'Jobinvolvement', 'Joblevel', 'Jobsatisfaction', 'Numcompaniesworked', 'Percentsalaryhike', 'Performancerating', 'Relationshipsatisfaction', 'Stockoptionlevel', 'Totalworkingyears', 'Trainingtimeslastyear', 'Worklifebalance', 'Yearsatcompany', 'Yearssincelastpromotion', 'Yearswithcurrmanager', 'Datebirth']

,Dailyrate,Distancefromhome,Education,Employeenumber,Environmentsatisfaction,Jobinvolvement,Joblevel,Jobsatisfaction,Numcompaniesworked,Percentsalaryhike,Performancerating,Relationshipsatisfaction,Stockoptionlevel,Totalworkingyears,Trainingtimeslastyear,Worklifebalance,Yearsatcompany,Yearssincelastpromotion,Yearswithcurrmanager,Datebirth
0,2015.72,6.0,3.0,1.0,1.0,3.0,5.0,3.0,7.0,13.0,3.0,3.0,0.0,10.0,5.0,3.0,20.0,15.0,15.0,1972.0
1,2063.39,1.0,4.0,2.0,3.0,2.0,5.0,3.0,0.0,14.0,3.0,1.0,1.0,34.0,5.0,3.0,33.0,11.0,9.0,1971.0
2,1984.25,4.0,2.0,3.0,3.0,3.0,5.0,4.0,1.0,11.0,3.0,4.0,0.0,22.0,3.0,3.0,22.0,11.0,15.0,1981.0
3,1771.40,2.0,4.0,4.0,1.0,3.0,4.0,3.0,3.0,19.0,3.0,2.0,2.0,10.0,2.0,3.0,20.0,5.0,6.0,1976.0
4,1582.77,3.0,3.0,5.0,1.0,4.0,4.0,1.0,2.0,12.0,3.0,4.0,1.0,10.0,5.0,3.0,19.0,2.0,8.0,1977.0

In [52]:
# 1. Definimos una función que convierte los valores a absolutos
def normalizar_distancia(columna):
    return columna.abs()   # abs() convierte -5 → 5, deja los positivos igual

# 2. Aplicamos la función a la columna 'distancefromhome'
df["Distancefromhome"] = normalizar_distancia(df["Distancefromhome"])

# 3. Revisamos las primeras filas para comprobar
print(df["Distancefromhome"].head(10))

0     6.0
1     1.0
2     4.0
3     2.0
4     3.0
5    22.0
6    25.0
7     1.0
8     2.0
9     9.0
Name: Distancefromhome, dtype: float64

In [53]:
df.head()

,Attrition,Businesstravel,Dailyrate,Department,Distancefromhome,Education,Educationfield,Employeenumber,Environmentsatisfaction,Gender,Jobinvolvement,Joblevel,Jobrole,Jobsatisfaction,Maritalstatus,Monthlyincome,Monthlyrate,Numcompaniesworked,Overtime,Percentsalaryhike,Performancerating,Relationshipsatisfaction,Standardhours,Stockoptionlevel,Totalworkingyears,Trainingtimeslastyear,Worklifebalance,Yearsatcompany,Yearssincelastpromotion,Yearswithcurrmanager,Datebirth,Salary,Roledepartament,Remotework
0,No,Unknown,2015.72,Unknown,6.0,3.0,Unknown,1.0,1.0,0.0,3.0,5.0,resEArch DIREcToR,3.0,Unknown,"16280,83$","42330,17$",7.0,No,13.0,3.0,3.0,Full Time,0.0,10.0,5.0,3.0,20.0,15.0,15.0,1972.0,"195370,00$",Unknown,yes
1,No,Unknown,2063.39,Unknown,1.0,4.0,Life Sciences,2.0,3.0,0.0,2.0,5.0,ManAGeR,3.0,Unknown,Unknown,"43331,17$",0.0,Unknown,14.0,3.0,1.0,Unknown,1.0,34.0,5.0,3.0,33.0,11.0,9.0,1971.0,"199990,00$",Unknown,yes
2,No,travel_rarely,1984.25,Research & Development,4.0,2.0,Technical Degree,3.0,3.0,0.0,3.0,5.0,ManaGER,4.0,Married,Unknown,"41669,33$",1.0,No,11.0,3.0,4.0,Unknown,0.0,22.0,3.0,3.0,22.0,11.0,15.0,1981.0,"192320,00$",ManaGER - Research & Development,yes
3,No,travel_rarely,1771.40,Unknown,2.0,4.0,Medical,4.0,1.0,1.0,3.0,4.0,ReseArCH DIrECtOr,3.0,Married,"14307,50$","37199,50$",3.0,Unknown,19.0,3.0,2.0,Full Time,2.0,10.0,2.0,3.0,20.0,5.0,6.0,1976.0,"171690,00$",Unknown,no
4,No,Unknown,1582.77,Unknown,3.0,3.0,Technical Degree,5.0,1.0,1.0,4.0,4.0,sAleS EXECUtIve,1.0,Divorced,"12783,92$","33238,20$",2.0,No,12.0,3.0,4.0,Unknown,1.0,10.0,5.0,3.0,19.0,2.0,8.0,1977.0,Unknown,Unknown,no

In [54]:
# Detectar valores únicos en columnas categóricas
columnas_categoricas = df.select_dtypes(include="object").columns

for col in columnas_categoricas:
    print(f"\nColumna: {col}")
    print(df[col].unique())

Columna: Attrition
['No' 'Yes']

Columna: Businesstravel
['Unknown' 'travel_rarely' 'travel_frequently' 'non-travel']

Columna: Department
['Unknown' 'Research & Development' 'Sales' 'Human Resources']

Columna: Educationfield
['Unknown' 'Life Sciences' 'Technical Degree' 'Medical' 'Other'
 'Marketing' 'Human Resources']

Columna: Gender
['0.0' '1.0']

Columna: Jobrole
['resEArch DIREcToR' 'ManAGeR' 'ManaGER' ... 'sAlES ExECUTivE'
 'SaLes ExecUtIVe' 'mAnUfactURInG DiRECTOr']

Columna: Maritalstatus
['Unknown' 'Married' 'Divorced' 'Single' 'divorced' 'Marreid']

Columna: Monthlyincome
['16280,83$' 'Unknown' '14307,50$' '12783,92$' '14311,67$' '8339,32$'
 '13829,17$' '15943,72$' '16644,17$' '15034,17$' '16038,33$' '4492,84$'
 '8956,67$' '5167,50$' '3334,17$' '8705,83$' '2675,00$' '8555,00$'
 '8729,17$' '3934,17$' '3845,83$' '14132,50$' '8588,33$' '4505,00$'
 '4918,33$' '4928,33$' '5538,33$' '11100,00$' '5572,50$' '11560,00$'
 '15870,83$' '13345,83$' '8010,83$' '3588,33$' '14205,00$' '4222,50$'
 '3076,67$' '2342,59$' '4789,17$' '8685,00$' '5289,17$' '1956,67$'
 '10408,33$' '6683,33$' '7452,50$' '16060,00$' '4647,50$' '2242,50$'
 '6169,17$' '7352,50$' '2982,50$' '14815,83$' '15177,50$' '15991,67$'
 '15989,17$' '8340,00$' '6656,67$' '5902,50$' '3935,83$' '2839,17$'
 '2440,83$' '10025,83$' '12855,83$' '5135,00$' '4271,67$' '8015,83$'
 '4175,00$' '15860,83$' '8666,67$' '2327,50$' '4728,33$' '7010,00$'
 '2790,00$' '4424,17$' '6378,33$' '10673,33$' '5488,33$' '2099,17$'
 '10933,33$' '2609,17$' '5561,67$' '14884,17$' '6205,00$' '11464,17$'
 '13831,67$' '2557,50$' '7700,83$' '5393,33$' '6934,17$' '7148,33$'
 '3497,50$' '8240,00$' '4730,83$' '7938,33$' '5687,50$' '3686,67$'
 '4534,17$' '5061,67$' '5143,33$' '4670,83$' '3599,17$' '2970,00$'
 '5217,50$' '5670,00$' '16196,67$' '4856,67$' '3901,67$' '1765,83$'
 '4978,33$' '11010,00$' '3375,83$' '4004,17$' '2284,17$' '7861,67$'
 '4496,67$' '9299,17$' '4133,33$' '7327,50$' '1846,67$' '9760,83$'
 '4420,00$' '9252,50$' '5526,67$' '6322,50$' '3612,50$' '4983,33$'
 '3536,67$' '4356,67$' '2250,00$' '1971,67$' '1940,83$' '8604,17$'
 '9037,50$' '5320,83$' '3050,00$' '7283,33$' '11249,17$' '2909,17$'
 '4350,00$' '8543,33$' '16450,00$' '5174,17$' '3778,33$' '7083,33$'
 '3865,83$' '4469,17$' '3400,83$' '8994,17$' '9042,50$' '3654,17$'
 '3388,33$' '4338,33$' '2212,50$' '2141,67$' '3751,67$' '4140,00$'
 '4289,17$' '2265,00$' '2949,17$' '4556,67$' '4844,17$' '8055,83$'
 '4729,17$' '6095,00$' '11308,33$' '8325,83$' '8540,00$' '9115,00$'
 '2160,83$' '9898,33$' '6745,83$' '14046,67$' '3780,83$' '3345,00$'
 '10618,33$' '8735,00$' '3540,83$' '5457,50$' '12009,17$' '6864,17$'
 '2675,83$' '13920,00$' '3806,67$' '4994,17$' '5415,83$' '5330,83$'
 '3018,33$' '5228,33$' '4573,33$' '2095,00$' '2663,33$' '2850,00$'
 '3405,83$' '3500,00$' '4171,67$' '5418,33$' '5290,83$' '3796,67$'
 '3525,00$' '8967,50$' '4336,67$' '14499,17$' '4295,83$' '15657,50$'
 '4069,17$' '2496,67$' '7731,67$' '3468,33$' '7377,50$' '6463,33$'
 '3324,17$' '3085,00$' '2254,17$' '3706,67$' '7448,33$' '8280,00$'
 '15616,67$' '4560,83$' '11252,50$' '11290,83$' '2311,67$' '7865,83$'
 '4387,50$' '3179,17$' '1990,83$' '3333,33$' '14653,33$' '4717,50$'
 '4057,50$' '3874,17$' '8746,67$' '2840,00$' '3548,33$' '4570,83$'
 '2318,33$' '5240,00$' '3495,00$' '2110,00$' '11438,33$' '3422,50$'
 '2997,50$' '3429,17$' '5226,67$' '7670,00$' '3644,17$' '1720,00$'
 '2025,00$' '4064,17$' '3133,33$' '1677,50$' '2305,00$' '5427,50$'
 '1855,00$' '4634,17$' '1786,67$' '4477,50$' '2414,17$' '4434,17$'
 '1667,50$' '3670,00$' '3286,67$' '15789,17$' '1678,33$' '11386,67$'
 '4184,17$' '3949,17$' '3597,50$' '1686,67$' '3274,17$' '3687,50$'
 '1940,00$' '2214,17$' '2185,00$' '2676,67$' '2425,83$' '1813,33$'
 '15554,17$' '5341,67$' '4117,50$' '3319,17$' '2420,00$' '2246,67$'
 '5629,17$' '9137,50$' '16171,67$' '5448,33$' '1881,67$' '2211,67$'
 '9945,83$' '3245,00$' '2000,00$' '2872,50$' '16260,83$' '2215,83$'
 '7372,50$' '4042,50$' '3814,17$' '11475,00$' '1914,17$' '2041,67$'
 '3618,33$' '2143,33$' '5416,67$' '2624,17$' '4436,67$' '3651,67$'
 '2127,50$' '4944,17$' '9111,67$' '1685,00$' '3546,67$' '2983,33$'
 '2415,83$' '4635,00$' '1980,83$' '2332,50$' '2876,67$' '2342,50$'
 '3647,50$' '3533,33$' '3522,50$' '3264,17$' '1701,67$' '2350,83$'
 '8297,50$' '1839,17$' '4775,83$' '3781,67$' '1733,33$' '3253,33$'
 '3855,83$' '1918,33$' '8830,00$' '4555,83$' '4807,50$' '1995,00$'
 '2690,83$' '13685,00$' '4705,83$' '1721,67$' '4571,67$' '2635,00$'
 '5542,50$' '2424,17$' '4081,67$' '2650,00$' '3390,83$' '5326,67$'
 '4045,83$' '2760,00$' '2150,00$' '1805,00$' '3645,00$' '4587,50$'
 '2155,83$' '13310,00$' '2860,83$' '2897,50$' '3255,83$' '2870,83$'
 '2300,00$' '5245,00$' '10930,00$' '2992,50$' '4504,17$' '1754,17$'
 '3251,67$' '2218,33$' '4589,17$' '6752,50$' '3315,00$' '4499,17$'
 '8706,67$' '3700,00$' '2216,67$' '2812,50$' '1890,83$' '2340,83$'
 '9045,00$' '2142,50$' '2849,17$' '2084,17$' '2138,33$' '3266,67$'
 '11636,67$' '5450,00$' '1870,00$' '13486,67$' '3527,50$' '12345,00$'
 '1931,67$' '16030,83$' '2126,67$' '2231,67$' '4898,33$' '3439,17$'
 '1790,00$' '5555,83$' '8103,33$' '2823,33$' '2531,67$' '1935,00$'
 '2438,33$' '3754,17$' '5560,83$' '11325,83$' '16264,17$' '16001,67$'
 '8373,33$' '2269,17$' '2634,17$' '1183,33$' '1000,00$' '4365,00$'
 '1975,00$' '5650,83$' '5544,17$' '2063,33$' '1904,17$' '2873,33$'
 '3798,33$' '1418,33$' '2136,67$' '3150,00$' '1950,00$' '1772,50$'
 '1694,17$' '8001,67$' '13855,83$' '1735,83$' '84083$' '6550,83$'
 '2201,67$' '4267,50$' '2245,00$' '4245,00$' '1928,33$' '1673,33$'
 '8793,33$' '1882,50$' '3469,17$' '15252,50$' '1983,33$' '3980,83$'
 '87667$' '6125,83$' '3971,67$' '2377,50$' '1755,83$' '1841,67$'
 '10992,50$' '15220,83$' '93167$' '2365,00$' '15050,83$' '1342,50$'
 '3973,33$' '2003,33$' '5323,33$' '4034,17$' '1728,33$' '2476,67$'
 '5679,17$' '2241,67$' '3489,17$' '9069,17$' '2385,00$' '5612,50$'
 '4411,67$' '2030,83$' '2463,33$' '3873,33$' '2336,67$' '2032,50$'
 '2380,00$' '2444,17$' '2385,83$' '2381,67$' '94083$' '16192,50$'
 '1923,33$' '2115,83$' '1980,00$' '4295,00$' '1811,67$' '2119,17$'
 '1848,33$' '2045,83$' '4380,83$' '2528,33$' '6993,33$' '15990,83$'
 '3578,33$' '3705,83$']

Columna: Monthlyrate
['42330,17$' '43331,17$' '41669,33$' '37199,50$' '33238,20$' '37210,33$'
 '21682,23$' '11681,39$' '35955,83$' '41453,67$' '43274,83$' '29037,67$'
 '28613,00$' '42347,50$' '39088,83$' '41699,67$' '23287,33$' '36296,00$'
 '13435,50$' '42997,50$' '8668,83$' '22635,17$' '34805,33$' '6955,00$'
 '22243,00$' '22695,83$' '13351,00$' '10228,83$' '6090,75$' '9999,17$'
 '36744,50$' '22329,67$' '11713,00$' '12787,67$' '23519,17$' '12813,67$'
 '14399,67$' '30274,83$' '28860,00$' '14488,50$' '10259,17$' '30056,00$'
 '41264,17$' '34699,17$' '20828,17$' '24938,33$' '9329,67$' '36933,00$'
 '10978,50$' '7999,33$' '43001,83$' '5000,67$' '12451,83$' '22581,00$'
 '13751,83$' '5087,33$' '6656,00$' '27061,67$' '17376,67$' '36980,67$'
 '19376,50$' '41756,00$' '12083,50$' '5830,50$' '16039,83$' '19116,50$'
 '7754,50$' '38521,17$' '39461,50$' '29416,83$' '41578,33$' '37099,83$'
 '41571,83$' '21684,00$' '17307,33$' '15346,50$' '10233,17$' '7381,83$'
 '6346,17$' '26067,17$' '33425,17$' '11106,33$' '20841,17$' '10855,00$'
 '41238,17$' '22533,33$' '6051,50$' '12293,67$' '41593,50$' '18226,00$'
 '7254,00$' '11502,83$' '16583,67$' '27750,67$' '14269,67$' '5457,83$'
 '37047,83$' '28426,67$' '6783,83$' '9628,67$' '14460,33$' '21346,00$'
 '38698,83$' '16133,00$' '29806,83$' '35962,33$' '9284,17$' '21935,33$'
 '21047,00$' '21502,00$' '24364,17$' '6649,50$' '20022,17$' '14022,67$'
 '6619,17$' '18028,83$' '6809,83$' '18585,67$' '9093,50$' '21424,00$'
 '28905,50$' '12300,17$' '6302,83$' '20639,67$' '14787,50$' '9585,33$'
 '11788,83$' '13160,33$' '13316,33$' '13372,67$' '10114,00$' '12144,17$'
 '9357,83$' '7722,00$' '13565,50$' '14742,00$' '42111,33$' '12627,33$'
 '5319,17$' '10952,50$' '10144,33$' '11390,17$' '4591,17$' '12943,67$'
 '6573,67$' '28626,00$' '18182,67$' '8777,17$' '10410,83$' '5938,83$'
 '11563,50$' '20440,33$' '11691,33$' '24177,83$' '10746,67$' '19051,50$'
 '41576,17$' '4801,33$' '25378,17$' '11492,00$' '24056,50$' '14369,33$'
 '16438,50$' '9392,50$' '12956,67$' '9195,33$' '11327,33$' '5850,00$'
 '5126,33$' '5046,17$' '9303,67$' '14570,83$' '22370,83$' '9635,17$'
 '23497,50$' '11856,00$' '13834,17$' '16304,17$' '7930,00$' '18936,67$'
 '29247,83$' '7563,83$' '11310,00$' '22212,67$' '42770,00$' '13452,83$'
 '15370,33$' '9823,67$' '18416,67$' '10051,17$' '11619,83$' '8842,17$'
 '7752,33$' '37544,00$' '23384,83$' '23510,50$' '22676,33$' '5117,67$'
 '13951,17$' '12499,50$' '9500,83$' '8809,67$' '11279,67$' '5752,50$'
 '5568,33$' '9754,33$' '10764,00$' '11151,83$' '5889,00$' '7667,83$'
 '11847,33$' '12594,83$' '20945,17$' '11167,00$' '12295,83$' '15847,00$'
 '11045,67$' '29401,67$' '14542,67$' '21647,17$' '22204,00$' '23699,00$'
 '5618,17$' '25735,67$' '17539,17$' '36521,33$' '9830,17$' '38835,33$'
 '8697,00$' '27607,67$' '7314,67$' '22711,00$' '9206,17$' '14189,50$'
 '31223,83$' '42436,33$' '17846,83$' '6957,17$' '36192,00$' '10343,67$'
 '9897,33$' '12984,83$' '14081,17$' '7479,33$' '13860,17$' '5904,17$'
 '7847,67$' '13390,00$' '13593,67$' '9492,17$' '5544,50$' '11890,67$'
 '5447,00$' '6924,67$' '7410,00$' '8855,17$' '11630,67$' '28028,00$'
 '9145,50$' '10753,17$' '9100,00$' '10846,33$' '16551,17$' '14087,67$'
 '29304,17$' '13756,17$' '13823,33$' '6721,00$' '9871,33$' '9165,00$'
 '10527,83$' '13697,67$' '23315,50$' '6441,50$' '11275,33$' '37697,83$'
 '36584,17$' '9366,50$' '11169,17$' '6361,33$' '40709,50$' '10579,83$'
 '4396,17$' '6491,33$' '20102,33$' '9017,67$' '19181,50$' '10564,67$'
 '4638,83$' '16804,67$' '8528,00$' '14824,33$' '8642,83$' '10681,67$'
 '8021,00$' '5860,83$' '9637,33$' '5154,50$' '11888,50$' '6088,33$'
 '19365,67$' '21528,00$' '11817,00$' '40603,33$' '11858,17$' '29256,50$'
 '29356,17$' '39372,67$' '6010,33$' '20451,17$' '11407,50$' '8265,83$'
 '5176,17$' '8666,67$' '38098,67$' '12265,50$' '10549,50$' '10072,83$'
 '22741,33$' '5997,33$' '7384,00$' '8135,83$' '4738,50$' '9225,67$'
 '11539,67$' '11884,17$' '6027,67$' '38217,83$' '13134,33$' '13624,00$'
 '7418,67$' '9087,00$' '5486,00$' '12276,33$' '29739,67$' '8898,50$'
 '7793,50$' '8915,83$' '13589,33$' '5453,50$' '8458,67$' '19942,00$'
 '9474,83$' '4472,00$' '5265,00$' '10566,83$' '8146,67$' '4361,50$'
 '6443,67$' '5993,00$' '7316,83$' '9128,17$' '14111,50$' '9282,00$'
 '4823,00$' '12048,83$' '4645,33$' '11641,50$' '6276,83$' '11528,83$'
 '11721,67$' '10508,33$' '4335,50$' '9542,00$' '8545,33$' '6413,33$'
 '41051,83$' '14007,50$' '5813,17$' '4363,67$' '7455,50$' '29605,33$'
 '10878,83$' '40828,67$' '10267,83$' '23075,00$' '9353,50$' '4385,33$'
 '6625,67$' '8512,83$' '9587,50$' '5044,00$' '5756,83$' '12870,00$'
 '5681,00$' '6959,33$' '6307,17$' '15017,17$' '4714,67$' '6998,33$'
 '40440,83$' '6042,83$' '13888,33$' '10705,50$' '8629,83$' '6292,00$'
 '5841,33$' '4710,33$' '14635,83$' '23757,50$' '5509,83$' '42046,33$'
 '14165,67$' '4892,33$' '4805,67$' '5750,33$' '25859,17$' '5516,33$'
 '8437,00$' '9234,33$' '22808,50$' '5200,00$' '7975,50$' '7468,50$'
 '42278,17$' '5761,17$' '19168,50$' '4430,83$' '10510,50$' '17593,33$'
 '9916,83$' '11710,83$' '8034,00$' '29835,00$' '4976,83$' '5308,33$'
 '9407,67$' '5572,67$' '14083,33$' '6822,83$' '11535,33$' '9494,33$'
 '5531,50$' '12854,83$' '9539,83$' '23690,33$' '4381,00$' '9221,33$'
 '7756,67$' '6281,17$' '12051,00$' '5150,17$' '5208,67$' '6064,50$'
 '6090,50$' '9483,50$' '9186,67$' '9158,50$' '8486,83$' '10766,17$'
 '4424,33$' '6112,17$' '21573,50$' '4781,83$' '4485,00$' '6047,17$'
 '17818,67$' '5655,00$' '12417,17$' '5501,17$' '5148,00$' '41342,17$'
 '5943,17$' '9832,33$' '8378,50$' '4506,67$' '4541,33$' '10025,17$'
 '4987,67$' '10987,17$' '22958,00$' '11845,17$' '5187,00$' '7862,83$'
 '20284,33$' '6996,17$' '35581,00$' '12235,17$' '9533,33$' '4476,33$'
 '11886,33$' '6851,00$' '14410,50$' '10612,33$' '6890,00$' '24362,00$'
 '8816,17$' '13849,33$' '10519,17$' '7176,00$' '6753,50$' '32937,67$'
 '5590,00$' '4693,00$' '9477,00$' '11927,50$' '5605,17$' '34606,00$'
 '4994,17$' '7438,17$' '7533,50$' '8465,17$' '7464,17$' '5980,00$'
 '13637,00$' '28418,00$' '7780,50$' '4560,83$' '8454,33$' '5767,67$'
 '4467,67$' '11931,83$' '17556,50$' '8619,00$' '11697,83$' '22637,33$'
 '9620,00$' '5763,33$' '7312,50$' '4916,17$' '10371,83$' '6086,17$'
 '23517,00$' '5570,50$' '13307,67$' '5408,00$' '7407,83$' '5418,83$'
 '5559,67$' '8493,33$' '30255,33$' '14170,00$' '4862,00$' '35065,33$'
 '9171,50$' '32097,00$' '37177,83$' '5022,33$' '7836,83$' '5815,33$'
 '41680,17$' '9581,00$' '5529,33$' '5802,33$' '11203,83$' '25818,00$'
 '20323,33$' '12735,67$' '5347,33$' '8941,83$' '4654,00$' '8419,67$'
 '14445,17$' '4528,33$' '4519,67$' '4227,17$' '6547,67$' '21068,67$'
 '7340,67$' '6582,33$' '5031,00$' '6339,67$' '9760,83$' '6142,50$'
 '14198,17$' '14458,17$' '29447,17$' '4716,83$' '42286,83$' '41604,33$'
 '21770,67$' '5899,83$' '14395,33$' '6848,83$' '3076,67$' '2600,00$'
 '11349,00$' '21634,17$' '34649,33$' '5135,00$' '14692,17$' '14414,83$'
 '6177,17$' '11392,33$' '5364,67$' '4950,83$' '7470,67$' '9875,67$'
 '3687,67$' '5555,33$' '10985,00$' '8190,00$' '21285,33$' '4069,00$'
 '5070,00$' '4608,50$' '4404,83$' '20804,33$' '36025,17$' '4513,17$'
 '2186,17$' '17032,17$' '5724,33$' '11095,50$' '5837,00$' '11037,00$'
 '4927,00$' '5013,67$' '5156,67$' '4350,67$' '22862,67$' '4894,50$'
 '5228,17$' '4595,50$' '5371,17$' '28587,00$' '9019,83$' '5633,33$'
 '39656,50$' '10350,17$' '2279,33$' '5332,17$' '5624,67$' '10244,00$'
 '15927,17$' '10326,33$' '6125,17$' '6181,50$' '4961,67$' '4565,17$'
 '4788,33$' '28580,50$' '39574,17$' '2422,33$' '5139,33$' '6149,00$'
 '39132,17$' '3490,50$' '10330,67$' '2760,33$' '5548,83$' '3386,50$'
 '13840,67$' '18148,00$' '10488,83$' '4493,67$' '6439,33$' '14765,83$'
 '5828,33$' '38061,83$' '3399,50$' '9071,83$' '7163,00$' '3018,17$'
 '23579,83$' '6201,00$' '14592,50$' '21138,00$' '11470,33$' '5280,17$'
 '8820,50$' '6404,67$' '10070,67$' '6075,33$' '5284,50$' '6188,00$'
 '6354,83$' '2363,83$' '11160,50$' '6203,17$' '6192,33$' '2446,17$'
 '42100,50$']

Columna: Overtime
['No' 'Unknown' 'Yes']

Columna: Standardhours
['Full Time' 'Unknown' 'Part Time']

Columna: Salary
['195370,00$' '199990,00$' '192320,00$' '171690,00$' 'Unknown'
 '100071,84$' '53914,11$' '165950,00$' '199730,00$' '134020,00$'
 '132060,00$' '195450,00$' '180410,00$' '192460,00$' '107480,00$'
 '167520,00$' '62010,00$' '198450,00$' '40010,00$' '104470,00$'
 '191324,62$' '160640,00$' '32100,00$' '102660,00$' '104750,00$'
 '61620,00$' '47210,00$' '153407,07$' '28111,13$' '46150,00$' '169590,00$'
 '54060,00$' '59020,00$' '108550,00$' '59140,00$' '66460,00$' '139730,00$'
 '66870,00$' '47350,00$' '138720,00$' '190450,00$' '96130,00$'
 '115100,00$' '170460,00$' '36920,00$' '198470,00$' '23080,00$'
 '57470,00$' '104220,00$' '63470,00$' '23480,00$' '30720,00$' '124900,00$'
 '80200,00$' '170680,00$' '89430,00$' '192720,00$' '55770,00$' '26910,00$'
 '74030,00$' '88230,00$' '35790,00$' '177790,00$' '182130,00$'
 '135770,00$' '191900,00$' '171230,00$' '191870,00$' '79880,00$'
 '70830,00$' '34070,00$' '29290,00$' '120310,00$' '154270,00$' '51260,00$'
 '96190,00$' '190330,00$' '104000,00$' '56740,00$' '191970,00$'
 '84120,00$' '33480,00$' '53090,00$' '76540,00$' '128080,00$' '65860,00$'
 '25190,00$' '170990,00$' '131200,00$' '44440,00$' '98520,00$'
 '178610,00$' '137570,00$' '165980,00$' '42850,00$' '101240,00$'
 '97140,00$' '99240,00$' '112450,00$' '92410,00$' '64720,00$' '30550,00$'
 '83210,00$' '31430,00$' '85780,00$' '98880,00$' '133410,00$' '29090,00$'
 '95260,00$' '44240,00$' '60740,00$' '61460,00$' '61720,00$' '46680,00$'
 '56050,00$' '43190,00$' '35640,00$' '62610,00$' '68040,00$' '194360,00$'
 '24550,00$' '50550,00$' '52570,00$' '59740,00$' '30340,00$' '83920,00$'
 '40510,00$' '48050,00$' '53370,00$' '94340,00$' '53960,00$' '111590,00$'
 '87930,00$' '191890,00$' '22160,00$' '117130,00$' '53040,00$'
 '111030,00$' '66320,00$' '75870,00$' '43350,00$' '59800,00$' '52280,00$'
 '27000,00$' '23660,00$' '23290,00$' '42940,00$' '67250,00$' '103250,00$'
 '44470,00$' '108450,00$' '54720,00$' '63850,00$' '75250,00$' '87400,00$'
 '134990,00$' '34910,00$' '102520,00$' '197400,00$' '62090,00$'
 '70940,00$' '45340,00$' '85000,00$' '46390,00$' '53630,00$' '40810,00$'
 '35780,00$' '173280,00$' '107930,00$' '108510,00$' '104660,00$'
 '23620,00$' '64390,00$' '57690,00$' '40660,00$' '52060,00$' '25700,00$'
 '45020,00$' '49680,00$' '51470,00$' '27180,00$' '54680,00$' '96670,00$'
 '51540,00$' '56750,00$' '73140,00$' '50980,00$' '135700,00$' '67120,00$'
 '99910,00$' '102480,00$' '25930,00$' '80950,00$' '168560,00$' '45370,00$'
 '179240,00$' '40140,00$' '127420,00$' '33760,00$' '104820,00$'
 '42490,00$' '195860,00$' '82370,00$' '47740,00$' '45680,00$' '59930,00$'
 '64990,00$' '34520,00$' '63970,00$' '27250,00$' '36220,00$' '61800,00$'
 '62740,00$' '43810,00$' '25590,00$' '54880,00$' '25140,00$' '31960,00$'
 '34200,00$' '53680,00$' '129360,00$' '42210,00$' '49630,00$' '76390,00$'
 '135250,00$' '63800,00$' '31020,00$' '45560,00$' '42300,00$' '48590,00$'
 '63220,00$' '107610,00$' '29730,00$' '52040,00$' '173990,00$'
 '168850,00$' '43230,00$' '51550,00$' '29360,00$' '187890,00$' '48830,00$'
 '20290,00$' '29960,00$' '92780,00$' '88530,00$' '48760,00$' '21410,00$'
 '39360,00$' '68420,00$' '39890,00$' '49300,00$' '27050,00$' '44480,00$'
 '23790,00$' '54870,00$' '28100,00$' '89380,00$' '99360,00$' '54540,00$'
 '54730,00$' '135030,00$' '135490,00$' '181720,00$' '27740,00$'
 '94390,00$' '52650,00$' '38150,00$' '23890,00$' '175840,00$' '48690,00$'
 '46490,00$' '104960,00$' '27680,00$' '34080,00$' '37550,00$' '21870,00$'
 '42580,00$' '53260,00$' '27820,00$' '176390,00$' '60620,00$' '62880,00$'
 '34240,00$' '41940,00$' '25320,00$' '56660,00$' '137260,00$' '41070,00$'
 '35970,00$' '41150,00$' '62720,00$' '25170,00$' '39040,00$' '92040,00$'
 '43730,00$' '20640,00$' '24300,00$' '48770,00$' '37600,00$' '29740,00$'
 '27660,00$' '33770,00$' '42130,00$' '65130,00$' '42840,00$' '22260,00$'
 '55610,00$' '53730,00$' '28970,00$' '54100,00$' '48500,00$' '39440,00$'
 '29600,00$' '189470,00$' '64650,00$' '26830,00$' '20140,00$' '34410,00$'
 '136640,00$' '50210,00$' '188440,00$' '106500,00$' '43170,00$'
 '20240,00$' '30580,00$' '39290,00$' '44250,00$' '23280,00$' '59400,00$'
 '26220,00$' '32120,00$' '29110,00$' '69310,00$' '21760,00$' '32300,00$'
 '186650,00$' '27890,00$' '64100,00$' '49410,00$' '39830,00$' '29040,00$'
 '21740,00$' '26570,00$' '109650,00$' '25430,00$' '194060,00$' '65380,00$'
 '22180,00$' '26540,00$' '119350,00$' '25460,00$' '38940,00$' '42620,00$'
 '105270,00$' '36810,00$' '34470,00$' '88470,00$' '20450,00$' '48510,00$'
 '81200,00$' '45770,00$' '54050,00$' '37080,00$' '137700,00$' '24500,00$'
 '43420,00$' '31490,00$' '53240,00$' '43820,00$' '25530,00$' '59330,00$'
 '44030,00$' '109340,00$' '20220,00$' '42560,00$' '28990,00$' '23770,00$'
 '24040,00$' '27990,00$' '28110,00$' '43770,00$' '42270,00$' '39170,00$'
 '49690,00$' '20420,00$' '22070,00$' '20700,00$' '27910,00$' '82240,00$'
 '26100,00$' '57310,00$' '25390,00$' '23760,00$' '190810,00$' '27430,00$'
 '45380,00$' '38670,00$' '20800,00$' '20960,00$' '46270,00$' '23020,00$'
 '50710,00$' '54670,00$' '23940,00$' '36290,00$' '93620,00$' '32290,00$'
 '164220,00$' '44000,00$' '20660,00$' '66510,00$' '48980,00$' '31800,00$'
 '112440,00$' '63920,00$' '33120,00$' '31170,00$' '152020,00$' '25800,00$'
 '21660,00$' '43740,00$' '55050,00$' '159720,00$' '23050,00$' '34770,00$'
 '39070,00$' '34450,00$' '27600,00$' '62940,00$' '21050,00$' '39020,00$'
 '20620,00$' '25870,00$' '55070,00$' '81030,00$' '39780,00$' '53990,00$'
 '44400,00$' '26600,00$' '33750,00$' '22690,00$' '47870,00$' '28090,00$'
 '25710,00$' '61420,00$' '24960,00$' '34190,00$' '25010,00$' '39200,00$'
 '65400,00$' '161840,00$' '171590,00$' '36170,00$' '26840,00$'
 '192370,00$' '44220,00$' '26780,00$' '51710,00$' '119160,00$' '93800,00$'
 '24680,00$' '41270,00$' '21480,00$' '38860,00$' '20900,00$' '20860,00$'

In [55]:

# 1. Seleccionamos solo columnas categóricas
columnas_categoricas = df.select_dtypes(include="object").columns

# 2. Mostramos valores únicos ANTES de corregir
print("=== VALORES ÚNICOS ANTES DE CORREGIR ===")
for col in columnas_categoricas:
    print(f"\nColumna: {col}")
    print(df[col].unique())

# 3. Correcciones manuales (ejemplos comunes, ajusta según tus datos)
correcciones = {
    "maritalstatus": {
        "Marreid": "Married",   # error tipográfico
        "Marrid": "Married"
    },
    "gender": {
        "Femal": "Female",
        "F": "Female",
        "M": "Male"
    },
    "jobrole": {
        "ManaGER": "Manager",
        "Sales Excecutive": "Sales Executive"
    },
    "department": {
        "Resarch & Development": "Research & Development"
    }
}

# 4. Aplicamos las correcciones
for col, reemplazos in correcciones.items():
    if col in df.columns:
        df[col] = df[col].replace(reemplazos)

# 5. Mostramos valores únicos DESPUÉS de corregir
print("\n=== VALORES ÚNICOS DESPUÉS DE CORREGIR ===")
for col in correcciones.keys():
    if col in df.columns:
        print(f"\nColumna: {col}")
        print(df[col].unique())

# 6. Vista rápida del DataFrame corregido
pd.set_option("display.max_columns", None)  # para ver todas las columnas
print("\n=== PRIMERAS FILAS DEL DF LIMPIO ===")
print(df.head(10))

=== VALORES ÚNICOS ANTES DE CORREGIR ===

Columna: Attrition
['No' 'Yes']

Columna: Businesstravel
['Unknown' 'travel_rarely' 'travel_frequently' 'non-travel']

Columna: Department
['Unknown' 'Research & Development' 'Sales' 'Human Resources']

Columna: Educationfield
['Unknown' 'Life Sciences' 'Technical Degree' 'Medical' 'Other'
 'Marketing' 'Human Resources']

Columna: Gender
['0.0' '1.0']

Columna: Jobrole
['resEArch DIREcToR' 'ManAGeR' 'ManaGER' ... 'sAlES ExECUTivE'
 'SaLes ExecUtIVe' 'mAnUfactURInG DiRECTOr']

Columna: Maritalstatus
['Unknown' 'Married' 'Divorced' 'Single' 'divorced' 'Marreid']

Columna: Monthlyincome
['16280,83$' 'Unknown' '14307,50$' '12783,92$' '14311,67$' '8339,32$'
 '13829,17$' '15943,72$' '16644,17$' '15034,17$' '16038,33$' '4492,84$'
 '8956,67$' '5167,50$' '3334,17$' '8705,83$' '2675,00$' '8555,00$'
 '8729,17$' '3934,17$' '3845,83$' '14132,50$' '8588,33$' '4505,00$'
 '4918,33$' '4928,33$' '5538,33$' '11100,00$' '5572,50$' '11560,00$'
 '15870,83$' '13345,83$' '8010,83$' '3588,33$' '14205,00$' '4222,50$'
 '3076,67$' '2342,59$' '4789,17$' '8685,00$' '5289,17$' '1956,67$'
 '10408,33$' '6683,33$' '7452,50$' '16060,00$' '4647,50$' '2242,50$'
 '6169,17$' '7352,50$' '2982,50$' '14815,83$' '15177,50$' '15991,67$'
 '15989,17$' '8340,00$' '6656,67$' '5902,50$' '3935,83$' '2839,17$'
 '2440,83$' '10025,83$' '12855,83$' '5135,00$' '4271,67$' '8015,83$'
 '4175,00$' '15860,83$' '8666,67$' '2327,50$' '4728,33$' '7010,00$'
 '2790,00$' '4424,17$' '6378,33$' '10673,33$' '5488,33$' '2099,17$'
 '10933,33$' '2609,17$' '5561,67$' '14884,17$' '6205,00$' '11464,17$'
 '13831,67$' '2557,50$' '7700,83$' '5393,33$' '6934,17$' '7148,33$'
 '3497,50$' '8240,00$' '4730,83$' '7938,33$' '5687,50$' '3686,67$'
 '4534,17$' '5061,67$' '5143,33$' '4670,83$' '3599,17$' '2970,00$'
 '5217,50$' '5670,00$' '16196,67$' '4856,67$' '3901,67$' '1765,83$'
 '4978,33$' '11010,00$' '3375,83$' '4004,17$' '2284,17$' '7861,67$'
 '4496,67$' '9299,17$' '4133,33$' '7327,50$' '1846,67$' '9760,83$'
 '4420,00$' '9252,50$' '5526,67$' '6322,50$' '3612,50$' '4983,33$'
 '3536,67$' '4356,67$' '2250,00$' '1971,67$' '1940,83$' '8604,17$'
 '9037,50$' '5320,83$' '3050,00$' '7283,33$' '11249,17$' '2909,17$'
 '4350,00$' '8543,33$' '16450,00$' '5174,17$' '3778,33$' '7083,33$'
 '3865,83$' '4469,17$' '3400,83$' '8994,17$' '9042,50$' '3654,17$'
 '3388,33$' '4338,33$' '2212,50$' '2141,67$' '3751,67$' '4140,00$'
 '4289,17$' '2265,00$' '2949,17$' '4556,67$' '4844,17$' '8055,83$'
 '4729,17$' '6095,00$' '11308,33$' '8325,83$' '8540,00$' '9115,00$'
 '2160,83$' '9898,33$' '6745,83$' '14046,67$' '3780,83$' '3345,00$'
 '10618,33$' '8735,00$' '3540,83$' '5457,50$' '12009,17$' '6864,17$'
 '2675,83$' '13920,00$' '3806,67$' '4994,17$' '5415,83$' '5330,83$'
 '3018,33$' '5228,33$' '4573,33$' '2095,00$' '2663,33$' '2850,00$'
 '3405,83$' '3500,00$' '4171,67$' '5418,33$' '5290,83$' '3796,67$'
 '3525,00$' '8967,50$' '4336,67$' '14499,17$' '4295,83$' '15657,50$'
 '4069,17$' '2496,67$' '7731,67$' '3468,33$' '7377,50$' '6463,33$'
 '3324,17$' '3085,00$' '2254,17$' '3706,67$' '7448,33$' '8280,00$'
 '15616,67$' '4560,83$' '11252,50$' '11290,83$' '2311,67$' '7865,83$'
 '4387,50$' '3179,17$' '1990,83$' '3333,33$' '14653,33$' '4717,50$'
 '4057,50$' '3874,17$' '8746,67$' '2840,00$' '3548,33$' '4570,83$'
 '2318,33$' '5240,00$' '3495,00$' '2110,00$' '11438,33$' '3422,50$'
 '2997,50$' '3429,17$' '5226,67$' '7670,00$' '3644,17$' '1720,00$'
 '2025,00$' '4064,17$' '3133,33$' '1677,50$' '2305,00$' '5427,50$'
 '1855,00$' '4634,17$' '1786,67$' '4477,50$' '2414,17$' '4434,17$'
 '1667,50$' '3670,00$' '3286,67$' '15789,17$' '1678,33$' '11386,67$'
 '4184,17$' '3949,17$' '3597,50$' '1686,67$' '3274,17$' '3687,50$'
 '1940,00$' '2214,17$' '2185,00$' '2676,67$' '2425,83$' '1813,33$'
 '15554,17$' '5341,67$' '4117,50$' '3319,17$' '2420,00$' '2246,67$'
 '5629,17$' '9137,50$' '16171,67$' '5448,33$' '1881,67$' '2211,67$'
 '9945,83$' '3245,00$' '2000,00$' '2872,50$' '16260,83$' '2215,83$'
 '7372,50$' '4042,50$' '3814,17$' '11475,00$' '1914,17$' '2041,67$'
 '3618,33$' '2143,33$' '5416,67$' '2624,17$' '4436,67$' '3651,67$'
 '2127,50$' '4944,17$' '9111,67$' '1685,00$' '3546,67$' '2983,33$'
 '2415,83$' '4635,00$' '1980,83$' '2332,50$' '2876,67$' '2342,50$'
 '3647,50$' '3533,33$' '3522,50$' '3264,17$' '1701,67$' '2350,83$'
 '8297,50$' '1839,17$' '4775,83$' '3781,67$' '1733,33$' '3253,33$'
 '3855,83$' '1918,33$' '8830,00$' '4555,83$' '4807,50$' '1995,00$'
 '2690,83$' '13685,00$' '4705,83$' '1721,67$' '4571,67$' '2635,00$'
 '5542,50$' '2424,17$' '4081,67$' '2650,00$' '3390,83$' '5326,67$'
 '4045,83$' '2760,00$' '2150,00$' '1805,00$' '3645,00$' '4587,50$'
 '2155,83$' '13310,00$' '2860,83$' '2897,50$' '3255,83$' '2870,83$'
 '2300,00$' '5245,00$' '10930,00$' '2992,50$' '4504,17$' '1754,17$'
 '3251,67$' '2218,33$' '4589,17$' '6752,50$' '3315,00$' '4499,17$'
 '8706,67$' '3700,00$' '2216,67$' '2812,50$' '1890,83$' '2340,83$'
 '9045,00$' '2142,50$' '2849,17$' '2084,17$' '2138,33$' '3266,67$'
 '11636,67$' '5450,00$' '1870,00$' '13486,67$' '3527,50$' '12345,00$'
 '1931,67$' '16030,83$' '2126,67$' '2231,67$' '4898,33$' '3439,17$'
 '1790,00$' '5555,83$' '8103,33$' '2823,33$' '2531,67$' '1935,00$'
 '2438,33$' '3754,17$' '5560,83$' '11325,83$' '16264,17$' '16001,67$'
 '8373,33$' '2269,17$' '2634,17$' '1183,33$' '1000,00$' '4365,00$'
 '1975,00$' '5650,83$' '5544,17$' '2063,33$' '1904,17$' '2873,33$'
 '3798,33$' '1418,33$' '2136,67$' '3150,00$' '1950,00$' '1772,50$'
 '1694,17$' '8001,67$' '13855,83$' '1735,83$' '84083$' '6550,83$'
 '2201,67$' '4267,50$' '2245,00$' '4245,00$' '1928,33$' '1673,33$'
 '8793,33$' '1882,50$' '3469,17$' '15252,50$' '1983,33$' '3980,83$'
 '87667$' '6125,83$' '3971,67$' '2377,50$' '1755,83$' '1841,67$'
 '10992,50$' '15220,83$' '93167$' '2365,00$' '15050,83$' '1342,50$'
 '3973,33$' '2003,33$' '5323,33$' '4034,17$' '1728,33$' '2476,67$'
 '5679,17$' '2241,67$' '3489,17$' '9069,17$' '2385,00$' '5612,50$'
 '4411,67$' '2030,83$' '2463,33$' '3873,33$' '2336,67$' '2032,50$'
 '2380,00$' '2444,17$' '2385,83$' '2381,67$' '94083$' '16192,50$'
 '1923,33$' '2115,83$' '1980,00$' '4295,00$' '1811,67$' '2119,17$'
 '1848,33$' '2045,83$' '4380,83$' '2528,33$' '6993,33$' '15990,83$'
 '3578,33$' '3705,83$']

Columna: Monthlyrate
['42330,17$' '43331,17$' '41669,33$' '37199,50$' '33238,20$' '37210,33$'
 '21682,23$' '11681,39$' '35955,83$' '41453,67$' '43274,83$' '29037,67$'
 '28613,00$' '42347,50$' '39088,83$' '41699,67$' '23287,33$' '36296,00$'
 '13435,50$' '42997,50$' '8668,83$' '22635,17$' '34805,33$' '6955,00$'
 '22243,00$' '22695,83$' '13351,00$' '10228,83$' '6090,75$' '9999,17$'
 '36744,50$' '22329,67$' '11713,00$' '12787,67$' '23519,17$' '12813,67$'
 '14399,67$' '30274,83$' '28860,00$' '14488,50$' '10259,17$' '30056,00$'
 '41264,17$' '34699,17$' '20828,17$' '24938,33$' '9329,67$' '36933,00$'
 '10978,50$' '7999,33$' '43001,83$' '5000,67$' '12451,83$' '22581,00$'
 '13751,83$' '5087,33$' '6656,00$' '27061,67$' '17376,67$' '36980,67$'
 '19376,50$' '41756,00$' '12083,50$' '5830,50$' '16039,83$' '19116,50$'
 '7754,50$' '38521,17$' '39461,50$' '29416,83$' '41578,33$' '37099,83$'
 '41571,83$' '21684,00$' '17307,33$' '15346,50$' '10233,17$' '7381,83$'
 '6346,17$' '26067,17$' '33425,17$' '11106,33$' '20841,17$' '10855,00$'
 '41238,17$' '22533,33$' '6051,50$' '12293,67$' '41593,50$' '18226,00$'
 '7254,00$' '11502,83$' '16583,67$' '27750,67$' '14269,67$' '5457,83$'
 '37047,83$' '28426,67$' '6783,83$' '9628,67$' '14460,33$' '21346,00$'
 '38698,83$' '16133,00$' '29806,83$' '35962,33$' '9284,17$' '21935,33$'
 '21047,00$' '21502,00$' '24364,17$' '6649,50$' '20022,17$' '14022,67$'
 '6619,17$' '18028,83$' '6809,83$' '18585,67$' '9093,50$' '21424,00$'
 '28905,50$' '12300,17$' '6302,83$' '20639,67$' '14787,50$' '9585,33$'
 '11788,83$' '13160,33$' '13316,33$' '13372,67$' '10114,00$' '12144,17$'
 '9357,83$' '7722,00$' '13565,50$' '14742,00$' '42111,33$' '12627,33$'
 '5319,17$' '10952,50$' '10144,33$' '11390,17$' '4591,17$' '12943,67$'
 '6573,67$' '28626,00$' '18182,67$' '8777,17$' '10410,83$' '5938,83$'
 '11563,50$' '20440,33$' '11691,33$' '24177,83$' '10746,67$' '19051,50$'
 '41576,17$' '4801,33$' '25378,17$' '11492,00$' '24056,50$' '14369,33$'
 '16438,50$' '9392,50$' '12956,67$' '9195,33$' '11327,33$' '5850,00$'
 '5126,33$' '5046,17$' '9303,67$' '14570,83$' '22370,83$' '9635,17$'
 '23497,50$' '11856,00$' '13834,17$' '16304,17$' '7930,00$' '18936,67$'
 '29247,83$' '7563,83$' '11310,00$' '22212,67$' '42770,00$' '13452,83$'
 '15370,33$' '9823,67$' '18416,67$' '10051,17$' '11619,83$' '8842,17$'
 '7752,33$' '37544,00$' '23384,83$' '23510,50$' '22676,33$' '5117,67$'
 '13951,17$' '12499,50$' '9500,83$' '8809,67$' '11279,67$' '5752,50$'
 '5568,33$' '9754,33$' '10764,00$' '11151,83$' '5889,00$' '7667,83$'
 '11847,33$' '12594,83$' '20945,17$' '11167,00$' '12295,83$' '15847,00$'
 '11045,67$' '29401,67$' '14542,67$' '21647,17$' '22204,00$' '23699,00$'
 '5618,17$' '25735,67$' '17539,17$' '36521,33$' '9830,17$' '38835,33$'
 '8697,00$' '27607,67$' '7314,67$' '22711,00$' '9206,17$' '14189,50$'
 '31223,83$' '42436,33$' '17846,83$' '6957,17$' '36192,00$' '10343,67$'
 '9897,33$' '12984,83$' '14081,17$' '7479,33$' '13860,17$' '5904,17$'
 '7847,67$' '13390,00$' '13593,67$' '9492,17$' '5544,50$' '11890,67$'
 '5447,00$' '6924,67$' '7410,00$' '8855,17$' '11630,67$' '28028,00$'
 '9145,50$' '10753,17$' '9100,00$' '10846,33$' '16551,17$' '14087,67$'
 '29304,17$' '13756,17$' '13823,33$' '6721,00$' '9871,33$' '9165,00$'
 '10527,83$' '13697,67$' '23315,50$' '6441,50$' '11275,33$' '37697,83$'
 '36584,17$' '9366,50$' '11169,17$' '6361,33$' '40709,50$' '10579,83$'
 '4396,17$' '6491,33$' '20102,33$' '9017,67$' '19181,50$' '10564,67$'
 '4638,83$' '16804,67$' '8528,00$' '14824,33$' '8642,83$' '10681,67$'
 '8021,00$' '5860,83$' '9637,33$' '5154,50$' '11888,50$' '6088,33$'
 '19365,67$' '21528,00$' '11817,00$' '40603,33$' '11858,17$' '29256,50$'
 '29356,17$' '39372,67$' '6010,33$' '20451,17$' '11407,50$' '8265,83$'
 '5176,17$' '8666,67$' '38098,67$' '12265,50$' '10549,50$' '10072,83$'
 '22741,33$' '5997,33$' '7384,00$' '8135,83$' '4738,50$' '9225,67$'
 '11539,67$' '11884,17$' '6027,67$' '38217,83$' '13134,33$' '13624,00$'
 '7418,67$' '9087,00$' '5486,00$' '12276,33$' '29739,67$' '8898,50$'
 '7793,50$' '8915,83$' '13589,33$' '5453,50$' '8458,67$' '19942,00$'
 '9474,83$' '4472,00$' '5265,00$' '10566,83$' '8146,67$' '4361,50$'
 '6443,67$' '5993,00$' '7316,83$' '9128,17$' '14111,50$' '9282,00$'
 '4823,00$' '12048,83$' '4645,33$' '11641,50$' '6276,83$' '11528,83$'
 '11721,67$' '10508,33$' '4335,50$' '9542,00$' '8545,33$' '6413,33$'
 '41051,83$' '14007,50$' '5813,17$' '4363,67$' '7455,50$' '29605,33$'
 '10878,83$' '40828,67$' '10267,83$' '23075,00$' '9353,50$' '4385,33$'
 '6625,67$' '8512,83$' '9587,50$' '5044,00$' '5756,83$' '12870,00$'
 '5681,00$' '6959,33$' '6307,17$' '15017,17$' '4714,67$' '6998,33$'
 '40440,83$' '6042,83$' '13888,33$' '10705,50$' '8629,83$' '6292,00$'
 '5841,33$' '4710,33$' '14635,83$' '23757,50$' '5509,83$' '42046,33$'
 '14165,67$' '4892,33$' '4805,67$' '5750,33$' '25859,17$' '5516,33$'
 '8437,00$' '9234,33$' '22808,50$' '5200,00$' '7975,50$' '7468,50$'
 '42278,17$' '5761,17$' '19168,50$' '4430,83$' '10510,50$' '17593,33$'
 '9916,83$' '11710,83$' '8034,00$' '29835,00$' '4976,83$' '5308,33$'
 '9407,67$' '5572,67$' '14083,33$' '6822,83$' '11535,33$' '9494,33$'
 '5531,50$' '12854,83$' '9539,83$' '23690,33$' '4381,00$' '9221,33$'
 '7756,67$' '6281,17$' '12051,00$' '5150,17$' '5208,67$' '6064,50$'
 '6090,50$' '9483,50$' '9186,67$' '9158,50$' '8486,83$' '10766,17$'
 '4424,33$' '6112,17$' '21573,50$' '4781,83$' '4485,00$' '6047,17$'
 '17818,67$' '5655,00$' '12417,17$' '5501,17$' '5148,00$' '41342,17$'
 '5943,17$' '9832,33$' '8378,50$' '4506,67$' '4541,33$' '10025,17$'
 '4987,67$' '10987,17$' '22958,00$' '11845,17$' '5187,00$' '7862,83$'
 '20284,33$' '6996,17$' '35581,00$' '12235,17$' '9533,33$' '4476,33$'
 '11886,33$' '6851,00$' '14410,50$' '10612,33$' '6890,00$' '24362,00$'
 '8816,17$' '13849,33$' '10519,17$' '7176,00$' '6753,50$' '32937,67$'
 '5590,00$' '4693,00$' '9477,00$' '11927,50$' '5605,17$' '34606,00$'
 '4994,17$' '7438,17$' '7533,50$' '8465,17$' '7464,17$' '5980,00$'
 '13637,00$' '28418,00$' '7780,50$' '4560,83$' '8454,33$' '5767,67$'
 '4467,67$' '11931,83$' '17556,50$' '8619,00$' '11697,83$' '22637,33$'
 '9620,00$' '5763,33$' '7312,50$' '4916,17$' '10371,83$' '6086,17$'
 '23517,00$' '5570,50$' '13307,67$' '5408,00$' '7407,83$' '5418,83$'
 '5559,67$' '8493,33$' '30255,33$' '14170,00$' '4862,00$' '35065,33$'
 '9171,50$' '32097,00$' '37177,83$' '5022,33$' '7836,83$' '5815,33$'
 '41680,17$' '9581,00$' '5529,33$' '5802,33$' '11203,83$' '25818,00$'
 '20323,33$' '12735,67$' '5347,33$' '8941,83$' '4654,00$' '8419,67$'
 '14445,17$' '4528,33$' '4519,67$' '4227,17$' '6547,67$' '21068,67$'
 '7340,67$' '6582,33$' '5031,00$' '6339,67$' '9760,83$' '6142,50$'
 '14198,17$' '14458,17$' '29447,17$' '4716,83$' '42286,83$' '41604,33$'
 '21770,67$' '5899,83$' '14395,33$' '6848,83$' '3076,67$' '2600,00$'
 '11349,00$' '21634,17$' '34649,33$' '5135,00$' '14692,17$' '14414,83$'
 '6177,17$' '11392,33$' '5364,67$' '4950,83$' '7470,67$' '9875,67$'
 '3687,67$' '5555,33$' '10985,00$' '8190,00$' '21285,33$' '4069,00$'
 '5070,00$' '4608,50$' '4404,83$' '20804,33$' '36025,17$' '4513,17$'
 '2186,17$' '17032,17$' '5724,33$' '11095,50$' '5837,00$' '11037,00$'
 '4927,00$' '5013,67$' '5156,67$' '4350,67$' '22862,67$' '4894,50$'
 '5228,17$' '4595,50$' '5371,17$' '28587,00$' '9019,83$' '5633,33$'
 '39656,50$' '10350,17$' '2279,33$' '5332,17$' '5624,67$' '10244,00$'
 '15927,17$' '10326,33$' '6125,17$' '6181,50$' '4961,67$' '4565,17$'
 '4788,33$' '28580,50$' '39574,17$' '2422,33$' '5139,33$' '6149,00$'
 '39132,17$' '3490,50$' '10330,67$' '2760,33$' '5548,83$' '3386,50$'
 '13840,67$' '18148,00$' '10488,83$' '4493,67$' '6439,33$' '14765,83$'
 '5828,33$' '38061,83$' '3399,50$' '9071,83$' '7163,00$' '3018,17$'
 '23579,83$' '6201,00$' '14592,50$' '21138,00$' '11470,33$' '5280,17$'
 '8820,50$' '6404,67$' '10070,67$' '6075,33$' '5284,50$' '6188,00$'
 '6354,83$' '2363,83$' '11160,50$' '6203,17$' '6192,33$' '2446,17$'
 '42100,50$']

Columna: Overtime
['No' 'Unknown' 'Yes']

Columna: Standardhours
['Full Time' 'Unknown' 'Part Time']

Columna: Salary
['195370,00$' '199990,00$' '192320,00$' '171690,00$' 'Unknown'
 '100071,84$' '53914,11$' '165950,00$' '199730,00$' '134020,00$'
 '132060,00$' '195450,00$' '180410,00$' '192460,00$' '107480,00$'
 '167520,00$' '62010,00$' '198450,00$' '40010,00$' '104470,00$'
 '191324,62$' '160640,00$' '32100,00$' '102660,00$' '104750,00$'
 '61620,00$' '47210,00$' '153407,07$' '28111,13$' '46150,00$' '169590,00$'
 '54060,00$' '59020,00$' '108550,00$' '59140,00$' '66460,00$' '139730,00$'
 '66870,00$' '47350,00$' '138720,00$' '190450,00$' '96130,00$'
 '115100,00$' '170460,00$' '36920,00$' '198470,00$' '23080,00$'
 '57470,00$' '104220,00$' '63470,00$' '23480,00$' '30720,00$' '124900,00$'
 '80200,00$' '170680,00$' '89430,00$' '192720,00$' '55770,00$' '26910,00$'
 '74030,00$' '88230,00$' '35790,00$' '177790,00$' '182130,00$'
 '135770,00$' '191900,00$' '171230,00$' '191870,00$' '79880,00$'
 '70830,00$' '34070,00$' '29290,00$' '120310,00$' '154270,00$' '51260,00$'
 '96190,00$' '190330,00$' '104000,00$' '56740,00$' '191970,00$'
 '84120,00$' '33480,00$' '53090,00$' '76540,00$' '128080,00$' '65860,00$'
 '25190,00$' '170990,00$' '131200,00$' '44440,00$' '98520,00$'
 '178610,00$' '137570,00$' '165980,00$' '42850,00$' '101240,00$'
 '97140,00$' '99240,00$' '112450,00$' '92410,00$' '64720,00$' '30550,00$'
 '83210,00$' '31430,00$' '85780,00$' '98880,00$' '133410,00$' '29090,00$'
 '95260,00$' '44240,00$' '60740,00$' '61460,00$' '61720,00$' '46680,00$'
 '56050,00$' '43190,00$' '35640,00$' '62610,00$' '68040,00$' '194360,00$'
 '24550,00$' '50550,00$' '52570,00$' '59740,00$' '30340,00$' '83920,00$'
 '40510,00$' '48050,00$' '53370,00$' '94340,00$' '53960,00$' '111590,00$'
 '87930,00$' '191890,00$' '22160,00$' '117130,00$' '53040,00$'
 '111030,00$' '66320,00$' '75870,00$' '43350,00$' '59800,00$' '52280,00$'
 '27000,00$' '23660,00$' '23290,00$' '42940,00$' '67250,00$' '103250,00$'
 '44470,00$' '108450,00$' '54720,00$' '63850,00$' '75250,00$' '87400,00$'
 '134990,00$' '34910,00$' '102520,00$' '197400,00$' '62090,00$'
 '70940,00$' '45340,00$' '85000,00$' '46390,00$' '53630,00$' '40810,00$'
 '35780,00$' '173280,00$' '107930,00$' '108510,00$' '104660,00$'
 '23620,00$' '64390,00$' '57690,00$' '40660,00$' '52060,00$' '25700,00$'
 '45020,00$' '49680,00$' '51470,00$' '27180,00$' '54680,00$' '96670,00$'
 '51540,00$' '56750,00$' '73140,00$' '50980,00$' '135700,00$' '67120,00$'
 '99910,00$' '102480,00$' '25930,00$' '80950,00$' '168560,00$' '45370,00$'
 '179240,00$' '40140,00$' '127420,00$' '33760,00$' '104820,00$'
 '42490,00$' '195860,00$' '82370,00$' '47740,00$' '45680,00$' '59930,00$'
 '64990,00$' '34520,00$' '63970,00$' '27250,00$' '36220,00$' '61800,00$'
 '62740,00$' '43810,00$' '25590,00$' '54880,00$' '25140,00$' '31960,00$'
 '34200,00$' '53680,00$' '129360,00$' '42210,00$' '49630,00$' '76390,00$'
 '135250,00$' '63800,00$' '31020,00$' '45560,00$' '42300,00$' '48590,00$'
 '63220,00$' '107610,00$' '29730,00$' '52040,00$' '173990,00$'
 '168850,00$' '43230,00$' '51550,00$' '29360,00$' '187890,00$' '48830,00$'
 '20290,00$' '29960,00$' '92780,00$' '88530,00$' '48760,00$' '21410,00$'
 '39360,00$' '68420,00$' '39890,00$' '49300,00$' '27050,00$' '44480,00$'
 '23790,00$' '54870,00$' '28100,00$' '89380,00$' '99360,00$' '54540,00$'
 '54730,00$' '135030,00$' '135490,00$' '181720,00$' '27740,00$'
 '94390,00$' '52650,00$' '38150,00$' '23890,00$' '175840,00$' '48690,00$'
 '46490,00$' '104960,00$' '27680,00$' '34080,00$' '37550,00$' '21870,00$'
 '42580,00$' '53260,00$' '27820,00$' '176390,00$' '60620,00$' '62880,00$'
 '34240,00$' '41940,00$' '25320,00$' '56660,00$' '137260,00$' '41070,00$'
 '35970,00$' '41150,00$' '62720,00$' '25170,00$' '39040,00$' '92040,00$'
 '43730,00$' '20640,00$' '24300,00$' '48770,00$' '37600,00$' '29740,00$'
 '27660,00$' '33770,00$' '42130,00$' '65130,00$' '42840,00$' '22260,00$'
 '55610,00$' '53730,00$' '28970,00$' '54100,00$' '48500,00$' '39440,00$'
 '29600,00$' '189470,00$' '64650,00$' '26830,00$' '20140,00$' '34410,00$'
 '136640,00$' '50210,00$' '188440,00$' '106500,00$' '43170,00$'
 '20240,00$' '30580,00$' '39290,00$' '44250,00$' '23280,00$' '59400,00$'
 '26220,00$' '32120,00$' '29110,00$' '69310,00$' '21760,00$' '32300,00$'
 '186650,00$' '27890,00$' '64100,00$' '49410,00$' '39830,00$' '29040,00$'
 '21740,00$' '26570,00$' '109650,00$' '25430,00$' '194060,00$' '65380,00$'
 '22180,00$' '26540,00$' '119350,00$' '25460,00$' '38940,00$' '42620,00$'
 '105270,00$' '36810,00$' '34470,00$' '88470,00$' '20450,00$' '48510,00$'
 '81200,00$' '45770,00$' '54050,00$' '37080,00$' '137700,00$' '24500,00$'
 '43420,00$' '31490,00$' '53240,00$' '43820,00$' '25530,00$' '59330,00$'
 '44030,00$' '109340,00$' '20220,00$' '42560,00$' '28990,00$' '23770,00$'
 '24040,00$' '27990,00$' '28110,00$' '43770,00$' '42270,00$' '39170,00$'
 '49690,00$' '20420,00$' '22070,00$' '20700,00$' '27910,00$' '82240,00$'
 '26100,00$' '57310,00$' '25390,00$' '23760,00$' '190810,00$' '27430,00$'
 '45380,00$' '38670,00$' '20800,00$' '20960,00$' '46270,00$' '23020,00$'
 '50710,00$' '54670,00$' '23940,00$' '36290,00$' '93620,00$' '32290,00$'
 '164220,00$' '44000,00$' '20660,00$' '66510,00$' '48980,00$' '31800,00$'
 '112440,00$' '63920,00$' '33120,00$' '31170,00$' '152020,00$' '25800,00$'
 '21660,00$' '43740,00$' '55050,00$' '159720,00$' '23050,00$' '34770,00$'
 '39070,00$' '34450,00$' '27600,00$' '62940,00$' '21050,00$' '39020,00$'
 '20620,00$' '25870,00$' '55070,00$' '81030,00$' '39780,00$' '53990,00$'
 '44400,00$' '26600,00$' '33750,00$' '22690,00$' '47870,00$' '28090,00$'
 '25710,00$' '61420,00$' '24960,00$' '34190,00$' '25010,00$' '39200,00$'
 '65400,00$' '161840,00$' '171590,00$' '36170,00$' '26840,00$'
 '192370,00$' '44220,00$' '26780,00$' '51710,00$' '119160,00$' '93800,00$'

In [56]:
df.head()

,Attrition,Businesstravel,Dailyrate,Department,Distancefromhome,Education,Educationfield,Employeenumber,Environmentsatisfaction,Gender,Jobinvolvement,Joblevel,Jobrole,Jobsatisfaction,Maritalstatus,Monthlyincome,Monthlyrate,Numcompaniesworked,Overtime,Percentsalaryhike,Performancerating,Relationshipsatisfaction,Standardhours,Stockoptionlevel,Totalworkingyears,Trainingtimeslastyear,Worklifebalance,Yearsatcompany,Yearssincelastpromotion,Yearswithcurrmanager,Datebirth,Salary,Roledepartament,Remotework
0,No,Unknown,2015.72,Unknown,6.0,3.0,Unknown,1.0,1.0,0.0,3.0,5.0,resEArch DIREcToR,3.0,Unknown,"16280,83$","42330,17$",7.0,No,13.0,3.0,3.0,Full Time,0.0,10.0,5.0,3.0,20.0,15.0,15.0,1972.0,"195370,00$",Unknown,yes
1,No,Unknown,2063.39,Unknown,1.0,4.0,Life Sciences,2.0,3.0,0.0,2.0,5.0,ManAGeR,3.0,Unknown,Unknown,"43331,17$",0.0,Unknown,14.0,3.0,1.0,Unknown,1.0,34.0,5.0,3.0,33.0,11.0,9.0,1971.0,"199990,00$",Unknown,yes
2,No,travel_rarely,1984.25,Research & Development,4.0,2.0,Technical Degree,3.0,3.0,0.0,3.0,5.0,ManaGER,4.0,Married,Unknown,"41669,33$",1.0,No,11.0,3.0,4.0,Unknown,0.0,22.0,3.0,3.0,22.0,11.0,15.0,1981.0,"192320,00$",ManaGER - Research & Development,yes
3,No,travel_rarely,1771.40,Unknown,2.0,4.0,Medical,4.0,1.0,1.0,3.0,4.0,ReseArCH DIrECtOr,3.0,Married,"14307,50$","37199,50$",3.0,Unknown,19.0,3.0,2.0,Full Time,2.0,10.0,2.0,3.0,20.0,5.0,6.0,1976.0,"171690,00$",Unknown,no
4,No,Unknown,1582.77,Unknown,3.0,3.0,Technical Degree,5.0,1.0,1.0,4.0,4.0,sAleS EXECUtIve,1.0,Divorced,"12783,92$","33238,20$",2.0,No,12.0,3.0,4.0,Unknown,1.0,10.0,5.0,3.0,19.0,2.0,8.0,1977.0,Unknown,Unknown,no

Guardamos en csv:

In [57]:
df.to_csv("Datos_para_visualizaciones.csv", index=False, encoding='utf-8')